In [ ]:
import numpy as np
import time

In [ ]:
def ExecutionTime(func):
  def inner(*args,**kwargs):
    start=time.perf_counter()
    res=func(*args,**kwargs)
    end=time.perf_counter()
    print("Execution time:", end - start, "seconds")
    return res
  return inner

@ExecutionTime
def Arithmeticoperations():
  arr1=np.array(list(map(int,input("Enter first array:").split())))
  arr2=np.array(list(map(int,input("Enter second array:").split())))
  print("Addition: ",arr1+arr2)
  print("Subtraction: ",arr1-arr2)
  print("Multiplication:",arr1*arr2)
  print("Division: ",arr1/arr2)
  print("Power: ",arr1**arr2)

@ExecutionTime
def StatisticalOperations():
  arr=np.array(list(map(int,input("Enter array with elements:").split())))
  print("mean:",np.mean(arr))
  print("median:",np.median(arr))
  print("maximum Element:",np.max(arr))
  print("minimum element:",np.min(arr))
  print("sum:",np.sum(arr))
  print("product:",np.prod(arr))
  print("Shape of an array:",arr.shape)
  print("Size of an array:",arr.size)
  print("Datatype of an array:",arr.dtype)


def ArrayManipulation():
  arr=np.array(list(map(int,input("Enter array with elements:").split())))
  @ExecutionTime
  def possib2D(arr):
    print("2D array possibilities")
    for i in range(1,(len(arr)//2)+1):
        value=len(arr)//i
        if i*value==len(arr):
          if i==1:
            print((i,value))
            print(arr.reshape(i,value))
            print((value,i))
            print(arr.reshape(value,i))
          else:
             print((i,value))
             print(arr.reshape(i,value))

  possib2D(arr)
  @ExecutionTime
  def possib3D(arr):
      print("3D possiblities")
      possib=()
      for i in range(1,(len(arr)//2)+1):
          for j in range(1,(len(arr)//2)+1):
              value=len(arr)//j
              if i*j*value==len(arr):
                  possib+=((i,j,value),(i,value,j),(j,i,value),(j,value,i),(value,i,j),(value,j,i))
      duplicates_remove=set(possib)
      for i in duplicates_remove:
          print(i)
          print(arr.reshape(i[0],i[1],i[2]))
  possib3D(arr)
  @ExecutionTime
  def srufsGm(arr):
      print("sorted array:",arr.sort())
      print("reverse sorting:",np.sort(arr)[::-1])
      print("unique elements:",np.unique(arr))
      print("first element: ",arr[0])
      print("second element:",arr[-1])
      mean_value=np.mean(arr)
      print("greater than mean:",arr[arr>mean_value])
  srufsGm(arr)

print('='*30)
print(" "*1,'Welcome to Numpy Calculator')
print('='*30)
while True:
  print("1.Arithmetic Opertions")
  print("2.Statistical Operations")
  print("3.Array Manipulation")
  print("4.exit")
  number=int(input("Enter the number between 1-4:"))

  try:
    if number==1:
      Arithmeticoperations()
    elif number==2:
      StatisticalOperations()
    elif number==3:
       ArrayManipulation()

    elif number==4:
      print("Thank you")
      break
    else:
      print("invalid number The number should be 0-4 only")
  except Exception as e:
    print(e)




  Welcome to Numpy Calculator
1.Arithmetic Opertions
2.Statistical Operations
3.Array Manipulation
4.exit
Enter the number between 1-4:1
Enter first array:1 2 34
Enter second array:23 3
operands could not be broadcast together with shapes (3,) (2,) 
1.Arithmetic Opertions
2.Statistical Operations
3.Array Manipulation
4.exit
Enter the number between 1-4:1
Enter first array:4 5 6 7 8
Enter second array:3 4 8 9 0


/tmp/ipython-input-3539930606.py:17: RuntimeWarning: divide by zero encountered in divide
  print("Division: ",arr1/arr2)


Addition:  [ 7  9 14 16  8]
Subtraction:  [ 1  1 -2 -2  8]
Multiplication: [12 20 48 63  0]
Division:  [1.33333333 1.25       0.75       0.77777778        inf]
Power:  [      64      625  1679616 40353607        1]
Execution time: 19.149701666000055 seconds
1.Arithmetic Opertions
2.Statistical Operations
3.Array Manipulation
4.exit
Enter the number between 1-4:1
Enter first array:4 5 6 7
Enter second array:5 6 7 8
Addition:  [ 9 11 13 15]
Subtraction:  [-1 -1 -1 -1]
Multiplication: [20 30 42 56]
Division:  [0.8        0.83333333 0.85714286 0.875     ]
Power:  [   1024   15625  279936 5764801]
Execution time: 7.062225408999893 seconds
1.Arithmetic Opertions
2.Statistical Operations
3.Array Manipulation
4.exit
Enter the number between 1-4:3
Enter array with elements:5 6 8 7
2D array possibilities
(1, 4)
[[5 6 8 7]]
(4, 1)
[[5]
 [6]
 [8]
 [7]]
(2, 2)
[[5 6]
 [8 7]]
3D possiblities
(4, 1, 1)
[[[5]]

 [[6]]

 [[8]]

 [[7]]]
(1, 2, 2)
[[[5 6]
  [8 7]]]
(2, 1, 2)
[[[5 6]]

 [[8 7]]]
(2, 2, 1)